name: vivid_play
description: VividPlay — Full MVP with SAF-friendly file picking, playlist reordering, background audio & polished UI.
publish_to: "none"
version: 0.0.4
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  video_player: ^2.5.0
  permission_handler: ^10.4.0
  just_audio: ^0.9.33
  audio_service: ^0.18.0
  audio_session: ^0.1.8
  path_provider: ^2.0.11
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  file_picker: ^5.2.5
  universal_io: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
